<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */
?>
<div
    class="z-30"
    x-data="initLiveChat()"
    x-bind="eventListeners"
    @keyup.escape="open = false"
    @click.outside="open = false"
>
    <?= /** @noEscape */ $block->getChildHtml('button') ?>

    <div
        class="livechat-wrapper"
        x-show="open"
        x-cloak
        x-transition
        role="dialog"
        aria-labelledby="livechat-title"
    >
        <div
            class="livechat"
            :class='{ ["layout-" + layout]: true }'
        >
            <?= /** @noEscape */ $block->getChildHtml('layout') ?>
        </div>
    </div>
</div>
